Use exceptions instead of ErrorStatus
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #12
Opened 2021-05-16 12:27 UTC by KarthikRIyer

I've just converted opentime ErrorStatus right now. Will work on opentimelineio subsequently.
I haven't deleted `io.opentime.ErrorStatus` yet because it might be used in opentimelineio tests. Once all conversions are done, I'll get rid of ErrorStatus entirely.

2021-05-19 21:39 UTC, reinecke requested changes
Looking really nice! The unittest examples show how much cleaner this is to use too!
One thing I'd like to avoid doing is ever raising just plain `Exception`, we should treat `OpenTimeException` and `OpenTimelineIOException` as the fail-safe exceptions.

Other than that, some small things, but I can't wait to start using it!

2021-05-19 21:39 UTC, reinecke commented on src/main/cpp/exceptions.cpp
> +    std::string otio_msg = "An OpenTime call failed with ";
Do we need the text "An OpenTime call failed with" at the beginning of the error message? Will the traceback make it clear that it came from an OpenTime call? If there are ways the context can be lost in the traceback (because of some JNI stuff), then maybe it's best to keep it. But if it's redundant we should address it.

2021-05-19 21:39 UTC, reinecke commented on src/main/cpp/exceptions.cpp
> +            const char *className = "java/lang/Exception";
Perhaps we should throw a base `OpenTimeException` here instead (this would be a direct subclass of `Exception`)?

2021-05-19 21:39 UTC, reinecke commented on src/main/cpp/exceptions.cpp
> +            const char *className = "java/lang/IllegalArgumentException";
Now that I look at these, `IllegalArgumentException` is unchecked which means consumers of the API aren't forced to handle it. Looking at [this Stack Overflow answer](https://stackoverflow.com/questions/15208544/when-should-an-illegalargumentexception-be-thrown), I agree with the author that is should be used for more obvious programmer error kinds of things.
Since these errors are related to "business logic" about time and can be caused by specific combinations of seemingly valid values (nonnull for example), perhaps we should throw something like an `OpenTimeException`.
Additionally, maybe we want to make specific `OpenTimeException` subclasses for some of these cases. This would allow users to differentiate between and better handle the specific error given their business domain.

2021-05-19 21:39 UTC, reinecke commented on src/main/cpp/exceptions.cpp
> +        case OTIO_NS::ErrorStatus::Outcome::KEY_NOT_FOUND: {
For `KEY_NOT_FOUND`, do you happen to know the cases where this comes up? I suspect users may want to explicitly catch and handle some of these cases.
If this is used in mapping-like objects, we may want to consider implementing the [Mapping interface](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html) instead (this would mean returning `null`).
If implementing the Mapping interface is the right answer, I think that would be out of scope for this PR. In that case I would suggest maybe we use `IndexOutOfBoundsException` for now and file a separate ticket to address this.

2021-05-19 21:39 UTC, reinecke commented on src/main/java/io/opentimeline/opentimelineio/exception/CannotComputeAvailableRangeException.java
> +        super("An OpenTimelineIO call failed with: " + message);
I'd suggest moving this logic into where the exception is thrown. This implicit behavior could be unpredictable to consumers of the class.

2021-05-19 22:19 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +      run: ./gradlew build -i
I was on Linux n wanted to see if the verbose output gave any info about why the test failed in Windows. But it didn't.

2021-05-19 22:19 UTC, KarthikRIyer commented on src/main/cpp/exceptions.cpp
> +            return env->ThrowNew(exClass, otio_msg.c_str());
Yes. That's a good idea. I'll do that.

2021-05-19 22:20 UTC, KarthikRIyer commented on src/main/cpp/exceptions.cpp
> +    std::string otio_msg = "An OpenTime call failed with ";
Ohh yeah. Forgot about the traceback 😅
I'll remove this extra text.

2021-05-19 22:24 UTC, KarthikRIyer commented on src/main/cpp/exceptions.cpp
> +        case OTIO_NS::ErrorStatus::Outcome::KEY_NOT_FOUND: {
It's present only in the deserialize function but I didn't understand when it would come up.

2021-05-25 01:39 UTC, reinecke approved these changes
Two very small comments. I think this is in a really great state - let me know how/if you want to address the two notes I left. Otherwise, I'm happy with it!

2021-05-25 01:39 UTC, reinecke commented on .github/workflows/gradle.yml
> +      run: ./gradlew build -i
Would it make sense to restore it back, since it was just there for debugging?

2021-05-25 01:39 UTC, reinecke commented on src/main/cpp/exceptions.cpp
> +        case OTIO_NS::ErrorStatus::Outcome::KEY_NOT_FOUND: {
It looks like it pops up in the `SerializableObject::Reader::read` family of functions - it's used when schema implementations are deserializing their fields.
For example, here is some usage in ImageSequenceReference: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/27adbc3c5f62aec8a2cd47b990a7f0507f48a9f2/src/opentimelineio/imageSequenceReference.cpp#L129-L135

So, maybe this should be something like a `SerializationException`?

2021-05-25 02:15 UTC, KarthikRIyer commented on src/main/cpp/exceptions.cpp
> +        case OTIO_NS::ErrorStatus::Outcome::KEY_NOT_FOUND: {
Shouldn't it be DeserializationException?

2021-05-25 02:20 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +      run: ./gradlew build -i
If it doesn't make a lot of difference, can we let this be? It might give some extra infowhen something breaks. For example, the expected and current value in an assertion when an assertion fails.

2021-05-25 04:01 UTC, reinecke commented on src/main/cpp/exceptions.cpp
> +        case OTIO_NS::ErrorStatus::Outcome::KEY_NOT_FOUND: {
Haha, yes :)

2021-05-25 04:02 UTC, reinecke commented on .github/workflows/gradle.yml
> +      run: ./gradlew build -i
I just like to avoid over-chatty logs where possible, it can sometime make it harder to find important info.  But if this is providing value, then it's totally fine.

2021-05-25 07:23 UTC, KarthikRIyer commented
Done!

2021-05-25 15:54 UTC, reinecke approved these changes

2021-05-25 15:55 UTC, merged