Load libraries on mac according to architecture
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #18
Opened 2021-07-16 07:48 UTC by KarthikRIyer

2021-07-16 18:21 UTC, reinecke requested changes
Nice add!

One suggestion - this might be a good opportunity to refactor this code a bit, it feels like it could use a dose of [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

For instance, every variant of `commandLine` for OS X starts with `'sh', '-c', 'mkdir -p build/natives && cd build/natives && cmake ../.. && cmake --build . --config Release && '`. Something like this would make the code more readable and maintainable (I wrote in python-ish syntax because I'm not that good at gradle stuff):
```
commandLine = ['sh', '-c', 'mkdir -p build/natives && cd build/natives && cmake ../.. && cmake --build . --config Release']
arch = System.getProperty("os.arch")
if arch in ["x86_64", "aarch64"]:
    commandLine += ['mv lib/Release/Darwin lib/Release/Darwin-' + arch]
}
```

This makes the code clear about what is common and what differs between the various cases.  This also protects against future errors when an argument needs to be added/changed/removed in all the cases.

The android code looks particularly repetitive, is there a way that command line could be built in a for-each loop?

2021-07-16 18:25 UTC, reinecke commented on src/main/java/io/opentimeline/LibraryLoader.java
> +                return "Darwin";
Do these actually need to branch loading on OS X? I think you should be able to combine all the OS X architectures into a single binary using [lipo](https://stackoverflow.com/questions/11120790/merge-static-libraries-into-single).

2021-07-16 18:30 UTC, reinecke commented
A couple other thoughts on this change:
Do you have access to an Apple Silicon Mac you've tried this on and run tests?

I'm a little reluctant to add this when our CI system isn't building and verifying it. At very least I feel a bit like we should add some documentation to the README that Apple Silicon support is experimental and untested. It may be worth adding a full architecture/OS support matrix to the README to set expectations clearly. We should make clear that since we can't run CI on Apple Silicon the pre-built JARs won't include support so you can't just add a gradle/maven dependency.

2021-07-16 19:10 UTC, KarthikRIyer commented
Yes. I tested it on an M1 macbook and the tests pass.

<img width="682" alt="Screenshot 2021-07-16 at 1 16 49 PM" src="https://user-images.githubusercontent.com/35020024/125997039-64af4be2-47b5-4eb8-9a7e-9b49df0edba2.png">

Adding the experimental Apple Silicon support to the README is a good idea. I'll do that. If we want to add a complete support matrix, should I also add build for 32-bit windows & linux?

2021-07-16 19:13 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/LibraryLoader.java
> +                return "Darwin";
Ohh, I did not know about lipo. According to the SO link it seems to be for static libs but we need dynamic libs here. I'll google a bit about this and see if we can also merge dynamic libs.

2021-07-16 19:17 UTC, KarthikRIyer commented
> it feels like it could use a dose of DRY.

Yes, I was thinking of this too. But I didn't think of the approach you suggested at the time. I'll implement that.

> The android code looks particularly repetitive, is there a way that command line could be built in a for-each loop?

I think this should be possible. I'll give it a try tomorrow morning.

2021-07-17 21:55 UTC, KarthikRIyer commented
32 bit Linux build works. It should be straightforward for windows too. But fir some reason cmake is not reconfiguring/rebuilding for 32 bit. :/

2021-07-18 17:14 UTC, KarthikRIyer commented
Phew! Linux (aarch32, aarch62, x86) and Windows (x86) support works now! It took so long to figure out how to get it to work :sweat_smile: 

I've used qemu to test the arm 32 and 64 bit versions on Linux. Not sure if there's something equivalent on Windows :thinking:

2021-07-19 20:27 UTC, KarthikRIyer commented
I tested this arm64 Windows on a VM (acc to [this](https://forums.macrumors.com/threads/success-virtualize-windows-10-for-arm-on-m1-with-alexander-grafs-qemu-hypervisor-patch.2272354/)). I didn't run all the tests but tried using the final JAR. It seems to work.

![Screenshot 2021-07-20 at 1 49 03 AM](https://user-images.githubusercontent.com/35020024/126222209-b02037e0-29c0-4796-9ecd-0257e8e6d63e.png)

I think we can tag it as EXPERIMENTAL too. On arm64 windows I had to use JDK 16 because arm64 windows jdk builds are available only for JDK 16. It's still in early access. Two arm64 JDKs are available ([openjdk](https://github.com/microsoft/openjdk-aarch64) & [zulu](https://www.azul.com/downloads/?os=windows&architecture=arm-64-bit&package=jdk)).

2021-07-20 19:08 UTC, reinecke requested changes
Overall, you're getting there. It still feels like there are some opportunities to make it more readable and maintainable though. I think the overall theme is that we want our code to gather things that are similar together and have the areas of logic focus on what differs between cases.

On a much more minor note, I think you may have accidentally checked in some `.sh` files you didn't intend to as well.

2021-07-20 19:13 UTC, KarthikRIyer commented on build.gradle
> +        new File('./aarch64javac.sh').withWriter('utf-8') {
I wanted the absolute path of the java & javac executables. gradle checks the java version (and some other stuff probably) before running the tests and it does that in a different working directory.

2021-07-20 19:32 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        rm -rf build/natives/CMakeCache.txt
The reason I'm doing this is to preserve the binaries generated by the previous build command.
For eg.
```
./gradlew build # 64 bit linux
./gradlew clean build # This will delete the complete build folder and we'll lose the 64 bit binaries
# Instead if we use this it'll just rebuild
rm -rf build/natives/CMakeCache.txt
./gradlew build --rerun-tasks
# we need to delete cache and can't just rerun tasks because then cmake reconfiguration won't happen
```

2021-07-20 19:34 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        wget https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-aarch64.tar.gz
I'm not sure about the license. But we're not redeploying any code. Just using it for testing.

2021-07-20 19:42 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/LibraryLoader.java
> +            if (System.getProperty("java.vm.name").toLowerCase().contains("dalvik"))
Acc. to [this](https://stackoverflow.com/a/19831208/9126612) SO answer, this is the correct way to verify the ART runtime:

```java
private boolean getIsArtInUse() {
    final String vmVersion = System.getProperty("java.vm.version");
    return vmVersion != null && vmVersion.startsWith("2");
}
```

2021-07-20 19:43 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/LibraryLoader.java
> +                return "Linux-amd64";
This is so much easier to read. Thanks for such a detailed review!

2021-07-20 20:05 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/LibraryLoader.java
> +            if (System.getProperty("java.vm.name").toLowerCase().contains("dalvik"))
I think we can leave this as it is, because the runtime name returned by "java.vm.name" on Android is till Dalvik. The version changes for ART.

On Android 8:
![image](https://user-images.githubusercontent.com/35020024/126388426-abf7fb7f-a438-4225-9ba1-622466642c33.png)

2021-07-20 20:41 UTC, KarthikRIyer commented on build.gradle
> +        new File('./aarch64javac.sh').withWriter('utf-8') {
I think `test.executable` needs an executable not a command. If I provide the command instead it gives me this error:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
        at 
.
.
.
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'qemu-aarch64 -L /usr/aarch64-linux-gnu/ /home/karthik/OpenTimelineIO-Java-Bindings/jdk8u292/bin/java''
.
.
.
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'qemu-aarch64 -L /usr/aarch64-linux-gnu/ /home/karthik/OpenTimelineIO-Java-Bindings/jdk8u292/bin/java'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
        ... 4 more
Caused by: java.io.IOException: Cannot run program "qemu-aarch64 -L /usr/aarch64-linux-gnu/ /home/karthik/OpenTimelineIO-Java-Bindings/jdk8u292/bin/java" (in directory "/home/karthik/.gradle/daemon/6.5"): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
        ... 8 more

```

2021-07-22 18:38 UTC, reinecke commented on build.gradle
> +        new File('./aarch64javac.sh').withWriter('utf-8') {
Okay, in that case since the build system is generating them, they should be treated like build artifacts, placed in the build folder, and not be checked in to git. Right?

2021-07-22 18:39 UTC, KarthikRIyer commented on build.gradle
> +        new File('./aarch64javac.sh').withWriter('utf-8') {
Yes. That's right. I've removed the files and added them to gitignore.

2021-07-22 18:44 UTC, reinecke commented on .github/workflows/gradle.yml
> +        wget https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-aarch64.tar.gz
Maybe you can do a little research into the licensing? We want to make sure we're compliant. Also, I'm a little unclear, are we using this JDK because it's prebuilt for aarch64?

It looks like the latest setup-java action may do this already: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Installing-custom-Java-architecture

2021-07-22 18:48 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        wget https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-aarch64.tar.gz
> Also, I'm a little unclear, are we using this JDK because it's prebuilt for aarch64?

Yes, that's right. This JVM will be able to use the aarch64 binaries. 

> It looks like the latest setup-java action may do this already

I don't think so, because GitHub actions does not provide ARM runners. But I'll try it out in a test repo anyways.

2021-07-22 18:52 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        wget https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-aarch64.tar.gz
![image](https://user-images.githubusercontent.com/35020024/126693241-79a8e90d-78c2-44f3-b0db-66aa01db4297.png)

GitHub Actions does not provide aarch64 JDK

2021-07-22 18:56 UTC, reinecke commented on .github/workflows/gradle.yml
> +        rm -rf build/natives/CMakeCache.txt
Having this sort of inter-step state management feels like it is likely to get broken at some point in the future. I wonder if we should consider adding a separate matrix dimension for architecture.

2021-07-22 18:59 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        wget https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-aarch64.tar.gz
Bellsoft JDK (Liberica JDK) License [here](https://github.com/bell-sw/Liberica/blob/master/LICENSE) is GNU GPL v2, which doesn't seem to be compatible with Apache 2.0 :(
![image](https://user-images.githubusercontent.com/35020024/126694388-2a0785cf-4d5e-4466-b17e-66a64dfcf0e8.png)

But since we're not reusing code or re-shipping any part of the code, will it be a problem?

2021-07-22 19:04 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        rm -rf build/natives/CMakeCache.txt
We could do that for windows and linux. Have to then figure out a way to properly pass the appropriate flags like `-Paarch64Build` and then recombining all binaries into the JAR will require some more work.

2021-07-22 21:14 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        wget https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-aarch64.tar.gz
AdoptOpenJDK builds have gplv2 license with classpath exception. So if I understand it correctly, in case we use any code from jdk in our project we're free to distribute it with any other license. Also, 

<img width="694" alt="Screenshot 2021-07-23 at 2 36 57 AM" src="https://user-images.githubusercontent.com/35020024/126710124-14fea58d-3752-4e33-9dd2-f5fb80eae02a.png">

So I think if we can get it to work with Adopt OpenJDK build, there shouldn't be any issue. But I'll have to try it out. I had some trouble with the Zulu JDK, so I had to use Liberica JDK.

2021-07-23 08:58 UTC, KarthikRIyer commented
Now the github actions files looks better to me. Feels more readable. And since all the builds happen in parallel, it's a bit faster. I moved the android build to a different workflow because I wanted the `combine` job to download all the binaries at once, and we don't want to include the android stuff there.

2021-08-05 20:41 UTC, reinecke commented on .github/workflows/gradle.yml
> +            architecture: aarch64
This is great, I love it!

2021-08-05 20:53 UTC, reinecke commented
Nice cleanup work! I think splitting a separate action for android was a good step. @KarthikRIyer It looks like `aarch32` is failing to build - mind taking a look? I think we can get this merged once that's resolved.

2021-08-06 00:17 UTC, KarthikRIyer commented
The fail seems to be due to some directoryname issue. I don't understand why that's happening. I'll take a look this weekend.

2021-08-21 07:29 UTC, KarthikRIyer commented
@reinecke fixed it. I hadn't installed qemu for the aarch32 build. :man_facepalming: We can merge this now.

2021-08-23 17:43 UTC, merged