Create workflow to publish to maven central
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #2
Opened 2021-02-16 18:56 UTC by KarthikRIyer

2021-02-16 20:55 UTC, reinecke requested changes
I know you're still somewhat WIP on this, I dropped a few quick notes in and look forward to the forthcoming updates!

2021-02-16 20:55 UTC, reinecke commented on .github/workflows/gradle.yml
> +    - name: Upload artefact
Nitpick: artifact

2021-02-16 20:55 UTC, reinecke commented on .github/workflows/gradle.yml
> +        uses: lukka/get-cmake@latest
This is convenient, however I'm a little weary of using community github actions unless they're really well analyzed - they could be vectors for injecting malicious code into our environment. Since, for the moment, this step will always run on ubuntu, can we just apt install a known OS package to achieve this?

2021-02-16 20:55 UTC, reinecke commented on .github/workflows/publish.yml
> +        echo $settings_xml > settings.xml
As discussed on slack, lets use printenv to avoid exposing secrets to the process table.

2021-02-16 20:55 UTC, reinecke commented on build.gradle
> +                    email ""
You can use the otio-discussion list for now: otio-discussion@lists.aswf.io

2021-02-16 21:22 UTC, reinecke commented on .github/workflows/gradle.yml
>        run: gradle build
Maybe double-check me on this, but should we be using `./gradlew` instead of plain `gradle`?

2021-02-16 21:28 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
>        run: gradle build
This shouldn't make much of a difference. ./gradlew first installs gradle then runs build
But we're already have gradle installed

2021-02-16 21:28 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        uses: lukka/get-cmake@latest
Yes. I'll make the change

2021-02-16 21:29 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +    - name: Upload artefact
British vs american spelling :sweat_smile:
I'll make the change

2021-02-17 04:40 UTC, reinecke commented on .github/workflows/gradle.yml
> +    - name: Upload artefact
Ahh, of course! No need to conform if you don't want to, you're very welcome to your cultural expression in that sort of case :)

2021-02-17 04:43 UTC, reinecke commented on .github/workflows/gradle.yml
>        run: gradle build
Wasn't sure if there might be some subtle difference in system cradle version vs. project grade version fetched by the wrapper. I trust whatever you find to be best practice.

2021-02-17 05:08 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
>        run: gradle build
Yes there might be a difference in the version. Using the wrapper is the best practice. I think we might have to generate a wrapper for Windows (gradlew.bat). I think that's why I simply used the gradle command.

2021-02-17 05:13 UTC, reinecke requested changes
Looks like it's getting really close, just a few more small notes.

2021-02-17 05:13 UTC, reinecke commented on .github/workflows/publish.yml
> +        rm -rf settings.xml
First, I'd drop the `-rf` from the `rm` command, since it's a regular file there's be no need to be so forceful :)

Second, I'm unclear in this context on whether or not this will get run should the previous three commands fail. We want to make sure that file disappears on both success and failure, but in the failure case we want a failure exit code to escalate to the CI system so it can signal something went wrong.

I presume you might be able to do this with something like:
```
{
    mvn ...first set of args... &&
    mvn ...second set of args... &&
    mvn ...third set of args.. ;
} || { rm settings.xml; exit 1 }
rm settings.xml
```
This is a bit annoying, but basically it runs the first three commands chained only of each succeeds in turn, then if the result of those three running was a failure, removes the settings.xml and aborts with a failure code. Otherwise, execution will continue and the settings.xml will be removed.

This is basically approximating this python construct:
```
try:
    ... do some things ...
finally:
   os.remove("settings.xml")
```

2021-02-17 05:15 UTC, reinecke commented on .github/workflows/publish.yml
> +        touch settings.xml; chmod 0644 settings.xml; echo $settings_xml > settings.xml
Oh, one more thing, should `echo $settings_xml > settings.xml` change to `printenv settings_xml > settings.xml`?

2021-02-17 05:20 UTC, KarthikRIyer commented on .github/workflows/publish.yml
> +        touch settings.xml; chmod 0644 settings.xml; echo $settings_xml > settings.xml
Missed this. Thanks!

2021-02-17 05:22 UTC, KarthikRIyer commented on .github/workflows/publish.yml
> +        rm -rf settings.xml
Ahh, we need to handle this case. I'll try it in a while.

2021-02-17 07:03 UTC, KarthikRIyer commented
PR Updated

2021-02-17 07:37 UTC, reinecke requested changes
One more change :)
This one's a good one, it lets us delete some code which means less code to maintain!

2021-02-17 07:37 UTC, reinecke commented on .github/workflows/gradle.yml
> +        fi
Looking at this, I think we have an opportunity to simplify here. 

1. Since both branches do the `./gradlew build`, it can be pulled out of the if structure and have a single call after:
```bash
if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
    chmod +x gradlew
elif [ "$RUNNER_OS" != 'Windows' ]; then
    echo "$RUNNER_OS not supported"
    exit 1
fi
./gradlew build
```

2. I don't think we even need any of this, I think you can set the file as executable in the repo using `git update-index --chmod=+x gradlew` then adding and committing the file: https://stackoverflow.com/a/40979016

Option 2 seems like the best bet to me!

2021-02-17 07:37 UTC, reinecke commented on .github/workflows/gradle.yml
> +          chmod +x gradlew
Should be able to omit this with the change from above.

2021-02-17 07:37 UTC, reinecke commented on .github/workflows/gradle.yml
> +          chmod +x gradlew
Can remove this one too.

2021-02-17 07:40 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +        fi
:open_mouth: this is nice

2021-02-17 07:57 UTC, KarthikRIyer commented
Done

2021-02-17 08:37 UTC, reinecke approved these changes

2021-02-17 08:37 UTC, reinecke commented
Looks good to me! I say squash and merge!

2021-02-18 01:33 UTC, merged