Update RREADME.MD
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #23
Opened 2021-07-23 16:03 UTC by jradha11

Replaced `gradle build` with `./gradlew build` as `gradle build` was giving build error for gradle version 7.1.1

2021-07-23 16:54 UTC, KarthikRIyer requested changes

2021-07-23 16:54 UTC, KarthikRIyer commented on README.md
> +If you're using `gradle build`, ensure `gradle` version to be 6.5.
If you're using a system-wide gradle installation, ensure the version to be 6.x.x.

2021-07-23 17:32 UTC, KarthikRIyer approved these changes

2021-08-05 03:47 UTC, KarthikRIyer commented
@reinecke we can merge this

2021-08-05 20:38 UTC, reinecke commented
Welcome @jradha11! Thanks for your contribution! Because we are part of the OpenTimelineIO project, we ask that you complete a contributor license agreement: https://opentimelineio.readthedocs.io/en/latest/tutorials/contributing.html#contributor-license-agreement

Once you've submit that, we can merge your addition!

2021-08-06 06:13 UTC, jradha11 commented
Hi @reinecke ! I have mailed my signed CLA form.

2021-08-06 20:49 UTC, reinecke commented
Received and filed, thanks for contributing!

2021-08-06 20:49 UTC, merged