[WIP] Add wrapper for clip_if() and children_if
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #27
Opened 2021-08-11 13:44 UTC by jradha11

2021-08-11 14:44 UTC, KarthikRIyer requested changes

2021-08-11 14:44 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/TimelineTest.java
> +                ()->{timeline.childrenIf(null, false);});
Split this into a separate test. Something like `testChildrenIfNullTimeRange`. And use the Test annotation like this:

`@Test(expected=NullPointerException.class)`

2021-08-11 14:44 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/TimelineTest.java
> +    public void testChildrenIf() throws ChildAlreadyParentedException{
Rename to something like `testChildrenIfEquality`

2021-08-11 14:44 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/TimelineTest.java
> +        List<Composable> result = timeline.childrenIf(search_range, false);
Add children (like clips, gaps, effects) to the Track and test those.

2021-08-11 14:44 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/TimelineTest.java
> +        }
Instead of closing these three in a separate try-catch block, use try with resources. See [this](https://stackoverflow.com/a/47175609) SO answer for reference. 

All OTIO objects implement the `AutoCloseable` interface. See [this](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) for reference. The gist is, when you use an autocloseable with `try with resources`, the `close` method is automatically called when the control exits the try block. We implement the `close` method and free any allocated resources (here, the native memory allocated) or close network connections, etc.

2021-08-12 11:04 UTC, jradha11 commented on src/test/java/io/opentimeline/TimelineTest.java
> +                ()->{timeline.childrenIf(null, false);});
`@Test(expected=NullPointerException.class)` is used in JUnit4. As we are using JUnit5, simple `assertThrows` would serve the purpose inside the test block.

2021-08-12 13:52 UTC, jradha11 commented on src/test/java/io/opentimeline/TimelineTest.java
> +        }
added tests using `try-with-resources`

2021-08-12 13:52 UTC, jradha11 commented on src/test/java/io/opentimeline/TimelineTest.java
> +        List<Composable> result = timeline.childrenIf(search_range, false);
Implemented

2021-08-12 13:54 UTC, jradha11 commented on src/test/java/io/opentimeline/TimelineTest.java
> +                ()->{timeline.childrenIf(null, false);});
Have seggregated the tests.

2021-08-12 14:01 UTC, jradha11 commented on src/test/java/io/opentimeline/TimelineTest.java
> +    public void testChildrenIf() throws ChildAlreadyParentedException{
Done

2021-08-12 15:16 UTC, KarthikRIyer requested changes

2021-08-12 15:16 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/opentimelineio/Timeline.java
> +    private native <T extends Composable> T[] childrenIfNative(TimeRange search_range, boolean shallow_search);
You need to be able to specify a `descendedFrom` parameter. Take a look at how it's impleented for `eachChild` [here](https://github.com/OpenTimelineIO/OpenTimelineIO-Java-Bindings/blob/cdf969d5c354a0e00e30d2b5272e7073848a4296/src/main/java/io/opentimeline/opentimelineio/Timeline.java#L146).

2021-08-12 15:16 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/TimelineTest.java
> +            }
Once you implement the `descendedFrom` parameter you should test getting only the clips.

2021-08-22 05:49 UTC, KarthikRIyer commented
@jradha11 This looks good. You might have missed a few Composable types like Stack. Could you please check if you've covered all of them?

Also, I would add a check in the tests for the size equality of the reference and result Lists.

2021-08-22 09:49 UTC, jradha11 commented
@KarthikRIyer 
Nice point about the test. I will check for length too in the equality cases. 
Also, I will be adding the remaining composable types - `Item`, `Composition`, `Transition`, and `Stack`.

2021-08-22 10:20 UTC, jradha11 commented on src/test/java/io/opentimeline/TimelineTest.java
> +            }
implemented

2021-08-22 14:26 UTC, KarthikRIyer commented
Looks good!

2021-08-22 15:00 UTC, jradha11 commented on src/main/java/io/opentimeline/opentimelineio/Timeline.java
> +    private native <T extends Composable> T[] childrenIfNative(TimeRange search_range, boolean shallow_search);
Implemented

2021-08-23 17:29 UTC, reinecke requested changes
Looking good! I had a few notes to help code readability and maintainability, but nothing major. Glad to have someone keeping the API up to date!

2021-08-23 17:29 UTC, reinecke commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    searchRange = timeRangeFromJObject(env, searchRangeTimeRange);
Could these two lines be combined since the `nullopt` value in `searchRange`  overwritten on the next line?

2021-08-23 17:29 UTC, reinecke commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
Looking at all these conditional branches, the only thing that varies between the cases is the return value, could all the code that is the same between cases be pulled up out of the conditional to remove the code duplication?

For example:
```
auto result = timeline->children_if<Clip>(&errorStatus, searchRange, shallowSearch);
processOTIOErrorStatus(env, errorStatus);
env->ReleaseStringUTFChars(name, str);
        
if(strcmp(str,"io.opentimeline.opentimelineio.Clip") == 0){
    return clipRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Clip>>(result)));
}
else if(strcmp(str,"io.opentimeline.opentimelineio.Track") == 0){
    return trackRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Track>>(result)));
}
...The rest of the cases
```

2021-08-23 17:29 UTC, reinecke commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    const char* str = env->GetStringUTFChars(name, NULL);
Consider giving these variables more descriptive names to help code readability. It can be difficult to understand the intended contents of a string named `str`.

2021-08-23 17:38 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    const char* str = env->GetStringUTFChars(name, NULL);
Sure, I will change with descriptive variable name.

2021-08-23 18:08 UTC, KarthikRIyer commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
@reinecke the template for children_if varies too.   I don't think we can pull out those statements. I don't like this solution too. I'm trying to see if there's something more elegant, but I haven't found anything yet.

2021-08-23 18:09 UTC, KarthikRIyer commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    const char* str = env->GetStringUTFChars(name, NULL);
I think this kind of bad naming is present throughout the JNI layer 😅

Maybe this change could be a different PR?

2021-08-24 05:25 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
@KarthikRIyer I'm working on an inline util to return the corresponding composable jObjectArray for `children_if`.  This will reduce code repetition.

2021-08-24 06:03 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
Also, we can remove the `processOTIOErrorStatus(env, errorStatus);` out of the conditional statements but `env->ReleaseStringUTFChars(name, str);` need to be executed before every return statement to free the memory allocated to `str`. If not executed then it'll lead to memory leaks which is causing the timeline tests to fail.

2021-08-24 08:08 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
@reinecke added generic util that can be used across classes using `children_if`

2021-08-24 08:47 UTC, KarthikRIyer commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
In your template util function, if you declare a jObjectArray before your if-else block, and assign the result to that variable, you should be able to pull out the string release function and put it after the if-else block.

jObjectArray is after all just a `_jobject` pointer, so this should work.
See the Reference Types section in the [JNI docs](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/types.html#primitive_types).

2021-08-24 09:02 UTC, KarthikRIyer commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
Also, @reinecke @jradha11 what do you think about a dispatch table pattern instead of `if-else`?
Something like std::map<std::string, std::function>?

@jradha11 if you are unfamiliar with this pattern, we use this in the [SVG adapter](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/6ce63ff7bdb5b90f66aa090d5689f566ca7b5b33/src/py-opentimelineio/opentimelineio/adapters/svg.py#L538) (it's in python but you'll get the gist).

2021-08-24 09:07 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
We can use a map to get the corresponding function for a `clsNameString`. Sounds about good to me. I'll see how it can be implemented here.

2021-08-24 17:41 UTC, reinecke commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    const char* str = env->GetStringUTFChars(name, NULL);
Oh, hah. If we're doing this same operation in a lot of places, it could be useful to create a function to abstract it. Yeah, if this is following some convention in the codebase, it's probably best to address it all at once in a separate PR. I prefer consistency in that case :)

2021-08-24 17:45 UTC, reinecke commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
I totally missed the `children_if` template parameter! In that case, if there is a way to factor out what's common, great, otherwise we do the best we can.

2021-09-03 11:03 UTC, jradha11 commented
@reinecke @KarthikRIyer 

I had an observation regarding CI check. In the last test that I added `testChildrenIfComposableEquality` in `CompositionTest.java` ( commit: b00d62d) , I got an exception: `UnsupportedOperationException: method not implemented for this class` as the verbose output ( that was because `range_of_all_children` was not implemented in `composition.cpp`). But still, there was no build error in spite of the exception in tests. I am attaching the screenshot of the verbose output. 

![Screenshot from 2021-09-03 16-29-36](https://user-images.githubusercontent.com/59576984/131995215-cd696f9c-27fe-417b-a552-9365a0e2b60c.png)
> error output

![Screenshot from 2021-09-03 16-29-45](https://user-images.githubusercontent.com/59576984/131995282-29535dad-86bf-41a0-9bf8-300f029a9410.png)
> successful build

I think we need to look into why CI didn't fail.

2021-09-03 18:08 UTC, reinecke commented
Yikes! Good catch!

2021-09-06 17:57 UTC, jradha11 commented
@KarthikRIyer 
Added dispatch table to remove the conditional statements. Please review!

Also I have removed childrenIf tests for Composition as the method has not been implemented. Should we keep the childrenIf wrapper too?

2021-09-06 18:07 UTC, KarthikRIyer commented
@jradha11  Yes, we should keep the children if wrapper. Classes that inherit from composition should inherit that method too. If you've wrapped all the methods please mark all the eachChild and eachClip methods as deprecated with the @Deprecated annotation.

I'll take a proper look at the commits in a day or two.

2021-09-06 18:28 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    const char* str = env->GetStringUTFChars(name, NULL);
I have tried to keep the naming comprehensible. As @KarthikRIyer said, we can improve on the conventions in a new PR. Shall I resolve it for now?

2021-09-06 18:28 UTC, jradha11 commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    return composableRetainerVectorToArray(env, *(new std::vector<SerializableObject::Retainer<Composable>>(result)));
Implemented the dispatch table.

2021-09-06 18:46 UTC, KarthikRIyer commented on src/main/cpp/io_opentimeline_opentimelineio_Timeline.cpp
> +    const char* str = env->GetStringUTFChars(name, NULL);
yes

2021-09-07 07:35 UTC, jradha11 commented
> @jradha11 Yes, we should keep the children if wrapper. Classes that inherit from composition should inherit that method too. If you've wrapped all the methods please mark all the eachChild and eachClip methods as deprecated with the @deprecated annotation.
> 
> I'll take a proper look at the commits in a day or two.

Added the @deprecated annotation.

2021-11-24 19:13 UTC, reinecke approved these changes

2021-11-25 06:18 UTC, reinecke reviewed
Just one question about the try/catch blocks in the tests.

2021-11-25 06:18 UTC, reinecke commented on src/test/java/io/opentimeline/StackTest.java
> +            e.printStackTrace();
Why is this in a try/catch block? I would expect `assertThrows` catches the expected exception and any others would appropriately fail the test and the test framework would output the trace, right?

Right now, unexpected exceptions would still pass unit testing, right?

2021-11-25 06:24 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/StackTest.java
> +            e.printStackTrace();
Good catch! I think she wanted to use try with resources to use the autocloseable functionality in Stack. But you're right. We shouldn;t use try catch here, and call close() instead.

2021-11-25 06:25 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/StackTest.java
> +            e.printStackTrace();
I wonder if something like this is the reason for issue #33 🤔

2021-11-25 06:30 UTC, KarthikRIyer commented on src/test/java/io/opentimeline/StackTest.java
> +            e.printStackTrace();
We can use try-finally instead of try-catch

2021-11-25 07:23 UTC, jradha11 commented on src/test/java/io/opentimeline/StackTest.java
> +            e.printStackTrace();
@reinecke I have a few submissions this weekend so I'll have a look from tuesday and work on the tests.

2022-01-15 14:57 UTC, KarthikRIyer requested changes

2022-01-15 14:57 UTC, KarthikRIyer commented on src/main/include/utilities.h
> +    jboolean ifPresent = env->CallObjectMethod(searchRangeTimeRange, isPresentID);
isPresent() returns a boolean.
It should be `env->CallObjectMethod(searchRangeTimeRange, getMethodID);`

2022-01-15 14:57 UTC, KarthikRIyer commented on src/main/include/utilities.h
> +    jmethodID isPresentID = env->GetMethodID(opt, "isPresent", "()Z;");
The method signature would be `()Z` instead of `()Z;`
semicolons are used after classes. boolean is a primitive type.

2022-01-15 14:57 UTC, KarthikRIyer commented on src/main/include/utilities.h
> +        jobject searchRangeJobject = env->CallObjectMethod(searchRangeTimeRange, getMethodID);
`searchRangeJObject` instead of `searchRangeJobject`

2022-01-15 14:57 UTC, KarthikRIyer commented on src/main/include/utilities.h
> +    jclass opt = env->GetObjectClass(searchRangeTimeRange);
`optionalClass` instead of `opt`

2022-01-15 14:58 UTC, KarthikRIyer commented
Could you also remove this plugin from the build.gradle file? We do not publish to bintray.

```groovy
dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.+'
    }
```

2022-01-15 15:42 UTC, KarthikRIyer commented on src/main/include/utilities.h
> +    jmethodID isPresentID = env->GetMethodID(opt, "isPresent", "()Z;");
It's not recommended to guess method signatures yourself.

You can use javap.

I did `javap -s java.util.Optional`

It gives you the signatures of all the methods in the class.

2022-01-31 14:34 UTC, KarthikRIyer commented
Looks good.
Tiny suggestion:
```cpp
JNIEXPORT jobjectArray JNICALL Java_io_opentimeline_opentimelineio_SerializableCollection_clipIfNative
        (JNIEnv *env, jobject thisObj, jobject searchRangeTimeRange, jboolean shallowSearch)
```

I would rename `searchRangeTimeRange` to `searchRangeTimeRangeOptional` everywhere, including the utility function. It'll be very clear that the value is an optional and cannot be used directly as a timerange.

2022-01-31 14:36 UTC, jradha11 commented
will do the change

2022-02-02 21:41 UTC, reinecke commented
I think we're pretty much there! One question, I saw tests for:

```java
// Make sure we find expected clips within range
track.childrenIf(Composable.class, Optional.of(search_range), false);
```

and:

```java
// Make sure null throws NullPointerException
track.childrenIf(Composable.class, null, false);
```

But I think we were missing:
```java
// Make sure full time range is traversed
track.childrenIf(Composable.class, Optional.empty(), false);
```

2022-02-03 11:06 UTC, jradha11 commented
oh yes! I must have missed this edge case. Will add them too!

2022-02-28 05:06 UTC, jradha11 commented
Hey @reinecke @KarthikRIyer ,
I have updated tests with the trimmed and full-time range. But, I was not able to do the same for SerialisableCollectionTest. I am not getting how to filter it. Could you please review and help me out here?

2022-02-28 18:26 UTC, reinecke commented
Oh wow, good catch. I just checked the python implementation and it doesn't seem to have a test for this case.
Looking at [the implementation](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/8f93157e2777536c2f90a871b21edbc492698a29/src/opentimelineio/serializableCollection.h#L82), I think it is designed to:

1. ignore search range for direct children
2. apply search range for child compositions if `shallow_search` is `false`

So, with `shallow_search` as `true`, I think `search_range` has no impact on the results of  `children_if` for `SerializableCollection`. With `shallow_search` set `false`, I think it returns all the children of the `SerializableCollection` and uses type-based behavior for the children it recurses into.

Does that make sense?

Since this test is for language bindings, I don't think it needs to be too rigorous around the behavior of c++ implementation, we just want our testing to verify all the parameters are being passed into the underlying implementation correctly.

2022-03-08 08:37 UTC, jradha11 commented
@reinecke 
Okay! Let me work around the `shallow_search` criteria to see if filtering works. Apart from that, is there anything that is left in this PR?

2022-03-19 16:44 UTC, KarthikRIyer commented
@jradha11 I think what @reinecke means is that if `shallow_search = true`, `search_range` is ignored.

If `shallow_search = false`, it will take `search_range` into consideration only for Compositions (like `Track`) inside the `SerializableCollection`. `Track` organises objects temporally (one after another). So I think a `search_range` for it makes sense. Since a `Stack` organise objects spatially (one over another), but it can contain tracks, `search_range` makes sense for it too. But a `SerializableCollection` is just a collection with no specific rules. So unless it has other compositions, a `search_range` doesn't mean anything.

So you could create a `Track` with 4 clips, add it to your `SerializableCollection` and check if `clipIf` works.

@reinecke please correct me if I'm wrong.

2022-03-21 05:43 UTC, jradha11 commented
@KarthikRIyer @reinecke I have made the changes. I'd love if you could review! :)

2022-04-05 17:49 UTC, reinecke commented
Looks Good! Thanks for seeing this through!

2022-04-05 17:49 UTC, merged