Build OTIO for Android and add GitHub Actions workflow
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #3
Opened 2021-03-05 16:10 UTC by KarthikRIyer

This PR adds code to build the lib for 64-bit Android.

We need to disable building of pybind11. The option to do that was added in a more recent commit to OTIO. But the minimum cmake version was also bumped up. The Android cmake toolchain is max 3.10.

2021-03-05 21:16 UTC, meshula reviewed
looks good, I have some questions!

2021-03-05 21:16 UTC, meshula commented on src/main/java/io/opentimeline/LibraryLoader.java
> +//        name += ("-" + OTIO_VERSION);
since this is removed (not commented) in the cmake, it makes sense to remove, not comment here

2021-03-05 21:16 UTC, meshula commented on src/main/java/io/opentimeline/NativeUtils.java
> +            System.out.println("here1");
unintentional debug output?

2021-03-05 21:16 UTC, meshula commented on src/main/java/io/opentimeline/NativeUtils.java
> +            System.out.println("here2: " + path);
unintentional debug leftovers?

2021-03-05 21:16 UTC, meshula commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
if you set the min to 3.10 do we get a ton of cmake-policy warnings in the output on mac/win/nix? If no, then I'm fine with setting 3.10.

2021-03-06 02:49 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/LibraryLoader.java
> +//        name += ("-" + OTIO_VERSION);
I was thinking, if the version in the shared lib is necessary?

For some reason the version  variable in cmake is empty when building for android, but works fine for other platforms. This is why I removed the version. It uses ninja instead of make. Could that be the reason?

2021-03-06 02:49 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/NativeUtils.java
> +            System.out.println("here1");
Oops. I'll remove it. Thanks

2021-03-06 02:54 UTC, KarthikRIyer commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
It's just on linux for now. No warnings.

2021-03-06 03:02 UTC, KarthikRIyer commented
When I tryy to build for 32-bit I get this error:

```console
> Task :compileJNI FAILED
-- The CXX compiler identification is Clang 11.0.5
-- Check for working CXX compiler: /home/karthik/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/karthik/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found JNI: NotNeeded  
-- The C compiler identification is Clang 11.0.5
-- Check for working C compiler: /home/karthik/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/karthik/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
true
-- Updating git submodules to make sure they are up to date
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
CMake Error at deps/OpenTimelineIO/src/deps/pybind11/tools/FindPythonLibsNew.cmake:125 (message):
  Python config failure: Python is 64-bit, chosen compiler is 32-bit
Call Stack (most recent call first):
  deps/OpenTimelineIO/src/deps/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  deps/OpenTimelineIO/src/deps/pybind11/CMakeLists.txt:33 (include)
```

Not sure how to tackle this without disabling pybind11. Any ideas?

@reinecke this is the error I was telling you about.

2021-03-06 05:37 UTC, meshula commented
When you build for Android, are you building the python bindings as well? Or just the C++? One possibility is skip the bindings. Otherwise, you need to set up some cmake variables to point to a python that is being packaged or available on your Android target, rather than the system python that exists while you are cross-compiling.

2021-03-06 05:39 UTC, KarthikRIyer commented
I want to disable the python bindings but there's no option to do that.

2021-03-06 06:37 UTC, KarthikRIyer commented
Sorry for the mess. I messed up the submodule while updating it :sweat_smile:

2021-03-29 18:36 UTC, reinecke requested changes
Just echoing some comments about the commented out lines, otherwise looks good.

2021-03-29 18:36 UTC, reinecke commented on build.gradle
> +//                            'mv lib/Release/Android/ lib/Release/x86_64'
Do we need all these commented out lines? can we just remove them instead?

2021-03-29 18:36 UTC, reinecke commented on build.gradle
> +//                commandLine 'sh', '-c', 'mkdir -p build/natives && cd build/natives && cmake ../.. && cmake --build . --config Release'
Another commented line that should be removed.

2021-03-29 19:25 UTC, reinecke approved these changes

2021-03-29 19:26 UTC, merged