Build system tweaks
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #47
Opened 2021-12-12 14:23 UTC by KarthikRIyer

- Add a flag to specify the parallel build level for C++/JNI code
- Delete build artifacts directory on rebuilding. (Right now the `mv` command fails because the renamed directory already exists. Deleting it on rebuilds fixes this issue.)

2022-02-04 21:09 UTC, reinecke requested changes
I think it's best if you can do a pass of this PR that avoids chaining commands in a subshell, the quoting and escaping required to do that could be error prone.
Using native gradle DSL tools for directory creation and removal will make the build system easier to understand, more portable, and less vulnerable to developer error or attacks.

2022-02-04 21:09 UTC, reinecke commented on build.gradle
> +                            'if [ -d "lib/Release/Linux-' + architecture + '" ]; then rm -rf lib/Release/Linux-' + architecture + '; fi && mv lib/Release/Linux lib/Release/Linux-' + architecture
Is this potentially dangerous? `architecture` could erroneously have a space added in and then the rm command isn't going to behave as expected and could delete things we don't want it to.
Rather than shell scripting this kind of thing, maybe we can we use [gradle delete](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Delete.html) to do it instead?

Embedding shell scripts that are of moderate complexity can be prone to errors - specifically with unquoted paths.

2022-02-04 21:09 UTC, reinecke commented on build.gradle
> +                    commandLine 'sh', '-c', 'mkdir -p build/natives && cd build/natives && cmake ../.. && cmake --build . --config Release ' + buildConcurrency
Can we use gradle commands to do the directory creation here? Anywhere where there are spaces used in a commandLine (as opposed to elements in an array) that is a red flag that we may be introducing some brittle, if not dangerous, code.

2022-02-04 21:09 UTC, reinecke commented on .github/workflows/gradle.yml
> +          ./gradlew build -P${ARCHITECTURE}Build -ParmJdkPath=${armJdkPath} -Pj=2
How did you decide on 2 as being the correct number? As I understand it, there is also some default that's used. According to cmake:
```
  --parallel [<jobs>], -j [<jobs>]
                 = Build in parallel using the given number of jobs.
                   If <jobs> is omitted the native build tool's
                   default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
```

What is the native build tool's default?

2022-02-04 21:20 UTC, KarthikRIyer commented on build.gradle
> +                            'if [ -d "lib/Release/Linux-' + architecture + '" ]; then rm -rf lib/Release/Linux-' + architecture + '; fi && mv lib/Release/Linux lib/Release/Linux-' + architecture
Yes. Using gradle DSL would be better. If we're not able to use gradle delete,I think we should be able to use standard Groovy or Java to accomplish this, since build.gradle is written in Groovy.

2022-02-04 21:27 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +          ./gradlew build -P${ARCHITECTURE}Build -ParmJdkPath=${armJdkPath} -Pj=2
It says [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) that GitHub Linux/Windows runners have a 2 core cpu. So i used 2. The native build tool (make) runs one build job at a time by default.

2022-02-04 22:33 UTC, reinecke commented on .github/workflows/gradle.yml
> +          ./gradlew build -P${ARCHITECTURE}Build -ParmJdkPath=${armJdkPath} -Pj=2
Got it.
In the [python build](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/d8d29118b36f075df4635a850404a00e71c8c71b/setup.py#L158), we query the number of processors and use that - perhaps that might be a more robust way to determine this?
Otherwise, if we hard-code to 2 then maybe it's best to just write a quick comment above about how that number was chosen.

2022-02-05 07:00 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +          ./gradlew build -P${ARCHITECTURE}Build -ParmJdkPath=${armJdkPath} -Pj=2
To get number of logical cores:

https://github.community/t/number-of-cores-as-env-context-variable/17396

2022-02-07 18:16 UTC, reinecke commented on .github/workflows/gradle.yml
> +          ./gradlew build -P${ARCHITECTURE}Build -ParmJdkPath=${armJdkPath} -Pj=2
It also looks like you can use java from within the gradle config to do this: https://discuss.gradle.org/t/set-maxparallelforks-to-number-of-cores-on-the-current-machine/4505

Perhaps using the link I put in could be the default in the gradle files if the new `-Pj` flag you created is unspecified? This seems like it would give the behavior most people would want by default but still provide a way to control if they like.

2022-02-07 18:28 UTC, KarthikRIyer commented on .github/workflows/gradle.yml
> +          ./gradlew build -P${ARCHITECTURE}Build -ParmJdkPath=${armJdkPath} -Pj=2
I like this idea!

2022-02-12 08:25 UTC, KarthikRIyer commented on build.gradle
>  }
Added this to fix build on mac.
Got an error on the M1 mac that couldn't process the down arrow symbol in the comments while creating the javadocs. Not sure about x64 macs.

```java
/**
     * The start of <b>this</b> precedes <b>other</b>.
     * <b>other</b> precedes the end of this.
     * other
     * ↓
     * *
     * [      this      ]
     *
     * @param other RationalTime to check for
     * @return does this contain other
     */
```

2022-02-12 08:25 UTC, KarthikRIyer commented
@reinecke refactored it to use java methods to create/delete/rename directories

2022-02-28 20:33 UTC, reinecke requested changes
This is getting closer, I think after your last refactor pass it became a bit more clear how we can further simplify the code.

The biggest thing that sticks out to me is that the windows/linux/macos compiler invocations seem mostly alike with small variants, but the android build process is very different.
To me, it feels like `compileJNI` should call functions like `invokeAndroidBuild`, `invokeNIXBuild`, and `invokeWindowsBuild`. I think it would be really beneficial if we could avoid passing space-delimited strings to `commandLine` and instead be always passing a list of args. When we use space-delimited strings we become vulnerable to injection attacks/errors.

2022-02-28 20:33 UTC, reinecke commented on build.gradle
> +                            'rm CMakeCache.txt'
This is still a lot of shell scripting embedded within a variable. It feels a bit like the `architectureCommandsMap` exists just for the multi-build case on android. I wonder if this whole thing might be simplified by creating a [separate method](https://stackoverflow.com/questions/27777591/how-to-define-and-call-custom-methods-in-build-gradle) altogether to handle android builds.

You could have something like:
```groovy
ext.buildForAndroid = { arch, sdk_path ->
    // Method body here
}
```

And then call this from within the for-loop. This would also allow you to avoid shelling out to `mv` and `rm` and use the safer gradle calls for that.

2022-02-28 20:33 UTC, reinecke commented on build.gradle
> +        }
There is no if-branch covering `OperatingSystem.current().isUnix()` even though you're checking for it elsewhere. Which `isUnix` operating systems are we supporting?

Also, there should be a final `else` condition to throw a human readable error like `"Operating system not supported: ${OperatingSystem.getDisplayName()}"`

2022-02-28 20:33 UTC, reinecke commented on build.gradle
> +                        project.hasProperty("aarch64Build") || project.hasProperty("aarch32Build")) {
It's hard to tell what the intention is here, consider taking everything in the test and making a variable like:
`def isARMBuild = (architecture == "aarch64" || architecture == "aarch32" || architecture == "x86" || project.hasProperty("aarch64Build") || project.hasProperty("aarch32Build"))`

2022-02-28 20:33 UTC, reinecke commented on build.gradle
>                  }
This conditional is unneeded because `cmakeToolchain` is already set to empty string above.

2022-03-01 12:43 UTC, KarthikRIyer commented
Thanks for the review @reinecke. I'll address the comments this weekend

2022-03-19 16:11 UTC, KarthikRIyer commented on build.gradle
> +        }
I did not notice this. Linux and macOS are `isUnix` OSes which we support. So we do not need this check. I've removed it.

2022-03-19 16:14 UTC, KarthikRIyer commented
Hi @reinecke 
I've made changes. I think I've covered all the things you pointed out. Please take a look and let me know if I missed something, or you find other improvement points.

2022-04-05 17:57 UTC, reinecke approved these changes
Looks Good!

2022-04-05 17:58 UTC, merged