Add enabled flag to Item
OpenTimelineIO/OpenTimelineIO-Java-Bindings pull request #57
Opened 2022-02-12 14:43 UTC by KarthikRIyer

Closes #56 

This PR adds:
- The enabled flag to Item.
- Proposes to add and further write tests in the BDD (Behaviour Driven Development) format.

The idea of BDD testing is to write tests in a simple user/business friendly manner. The tests become a documentation in themselves. For example:

If we want to write a simple test to see if disabling an `Item` works...

The BDD specification would be like:

```
given: "An item is created"
when: "Item is disabled"
then: "Item does not contribute to the composition"
```

And the code would be like: 

```groovy
given: "An item is created"
def item = new Item()
verify {
    item.enabled() == true
}

when: "Item is disabled"
item.setEnabled(false)

then: "Item does not contribute to the composition"
verifyAll {
        item.isEnabled() == false
}
```

I've used [spock](https://spockframework.org/), a groovy BDD testing framework. It might be a lot of effort in the beginning but once you get used to it, it becomes simpler and clearer. It'll also be helpful to community members new to the project. The current tests might not be very clear to them. 
Spock also has an extension [spock-reports](https://github.com/renatoathaydes/spock-reports) that generates nice HTML test reports. But I haven't been able to get it working with the bindings yet.

Any thoughts on taking this forward? Or should we continue writing unit test as we do right now?

If we do take it forward, we might also want to adopt this for the python bindings. There are plenty of frameworks available, but in particular `pytest-bdd` is compatible with pytest. ([Framework comparison](https://automationpanda.com/2019/04/02/python-bdd-framework-comparison/))

@reinecke @meshula @jminor @ssteinbach

2022-02-17 18:04 UTC, KarthikRIyer commented
Spock reports now works!

![image](https://user-images.githubusercontent.com/35020024/154542362-27c7c082-8c89-439f-be58-111fa4bd1eec.png)
![image](https://user-images.githubusercontent.com/35020024/154543230-d78bb959-61de-440b-b1a0-ea8182072aec.png)

2022-02-28 18:59 UTC, KarthikRIyer commented
Hi @reinecke, could you please take a look at this too

2022-02-28 20:50 UTC, reinecke requested changes
In terms of `isEnabled` - one small question on deprecating the old constructor.

On BDD testing:

I support migrating to spock tests for our Java implementation, however I would prefer that we do that its own separate PR.

In terms of BDD testing in python, I think that choice is entangled with some language-specific details (like which frameworks we use, what the current best practice in the community is), so we should have that discussion on an issue in the [main repo](https://github.com/PixarAnimationStudios/OpenTimelineIO).

2022-02-28 20:50 UTC, reinecke commented on src/main/java/io/opentimeline/opentimelineio/Item.java
>      }
Should we mark this constructor with an `@Deprecated` to encourage people toward the constructor that best matches the underlying implementation?

2022-03-01 07:55 UTC, KarthikRIyer commented on src/main/java/io/opentimeline/opentimelineio/Item.java
>      }
Yes. I'll make the change

2022-03-19 16:15 UTC, KarthikRIyer commented
@reinecke this PR only has the wrapper for the new flag now. I think this is good to merge.

2022-04-05 17:52 UTC, reinecke approved these changes
Thanks for taking care of this!

2022-04-05 17:53 UTC, merged